In [2]:
pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.2.7-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
Requirement already satisfied: pandas>=1.2.0 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pyreadstat) (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas>=1.2.0->pyreadstat) (1.26.4)
Requirement already satisfied: six>=1.5 in c:\users\benedict\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)
Downloading pyreadstat-1.2.7-cp310-cp310-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
    --------------------------------------- 0.0/2.4 MB 991.0 kB/s eta 0:00:03
   ---- ----------------------------------- 0.3/2.4 MB 3.4 MB/s eta 0:00:01
   ------------------ --------------------- 1.1/2.4 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------  2.4/2.4 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 12.9 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.7
Note: you may need to restart the kernel to use updated packages.

In [11]:
import os
import pandas as pd

In [13]:
# Base directories
base_dirs = {
    'Data Wave 2022': '2022',
    'Data Wave 2023': '2023'
}

# Dictionary to store DataFrames
dataframes = {}

In [15]:
# Print the current working directory
current_working_directory = os.getcwd()
print(f"Current Working Directory: {current_working_directory}")

# List all files and directories in the current working directory
print("Files and directories in the current working directory:")
for item in os.listdir(current_working_directory):
    print(item)

Current Working Directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS
Files and directories in the current working directory:
.git
Data Loading.ipynb
Data Wave 2022
Data Wave 2023
README.md

In [17]:
# Verify that base directories exist
for base_dir in base_dirs.keys():
    full_path = os.path.join(current_working_directory, base_dir)
    if not os.path.exists(full_path):
        print(f"Base directory does not exist: {full_path}")
    else:
        print(f"Found base directory: {full_path}")

Found base directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022
Found base directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023

In [16]:
# Function to process .sav files
def process_sav_file(file_path, folder_name, year):
    try:
        data = pd.read_spss(file_path)
        print(f"Successfully read {file_path}")
        # Create a key for the DataFrame dictionary
        key = f"{folder_name} {year}"
        dataframes[key] = data
    except Exception as e:
        print(f"Error reading {file_path}: {e}")

In [18]:
# Iterate through the base directories
for base_dir, year in base_dirs.items():
    full_path = os.path.join(current_working_directory, base_dir)
    for root, dirs, files in os.walk(full_path):
        print(f"Exploring directory: {root}")  # Debugging output
        for file in files:
            if file.endswith('.sav'):
                folder_name = os.path.basename(root)
                file_path = os.path.join(root, file)
                print(f"Found .sav file: {file_path}")  # Debugging output
                process_sav_file(file_path, folder_name, year)

Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Code books
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGI module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGI module\agi2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGI module\agi2022en_spss_1.0\agi2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGI module\agi2022en_spss_1.0\agi2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGW module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGW module\agw2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGW module\agw2022en_spss_1.0\agw2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data AGW module\agw2022en_spss_1.0\agw2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HHI module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HHI module\hhi2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HHI module\hhi2022en_spss_1.0\hhi2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HHI module\hhi2022en_spss_1.0\hhi2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HSE module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HSE module\hse2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HSE module\hse2022en_spss_1.0\hse2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data HSE module\hse2022en_spss_1.0\hse2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data INC module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data INC module\inc2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data INC module\inc2022en_spss_1.0\inc2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data INC module\inc2022en_spss_1.0\inc2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data PSY module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data PSY module\psy2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data PSY module\psy2022en_spss_1.0\psy2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data PSY module\psy2022en_spss_1.0\psy2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WRK module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WRK module\wrk2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WRK module\wrk2022en_spss_1.0\wrk2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WRK module\wrk2022en_spss_1.0\wrk2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WTH module
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WTH module\wth2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WTH module\wth2022en_spss_1.0\wth2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Data WTH module\wth2022en_spss_1.0\wth2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Weights
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Weights\weights2022en_spss_1.0
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Weights\weights2022en_spss_1.0\weights2022en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2022\Weights\weights2022en_spss_1.0\weights2022en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Code books
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGI module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGI module\agi2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGI module\agi2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGW module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGW module\agw2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data AGW module\agw2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HHI module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HHI module\hhi2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HHI module\hhi2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HSE module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HSE module\hse2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data HSE module\hse2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data INC module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data INC module\inc2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data INC module\inc2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data PSY module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data PSY module\psy2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data PSY module\psy2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WRK module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WRK module\wrk2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WRK module\wrk2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WTH module
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WTH module\wth2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Data WTH module\wth2023en_1.0.sav
Exploring directory: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Weights
Found .sav file: c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Weights\weights2023en_1.0.sav
Successfully read c:\Users\Benedict\Desktop\Business Analytics and Econometrics\SS24\Topics in Econometrics and Statistics\DHS\DHS\Data Wave 2023\Weights\weights2023en_1.0.sav

In [19]:
# Check the contents of the dataframes dictionary
print("DataFrames keys:", list(dataframes.keys()))  # Debugging output

DataFrames keys: ['agi2022en_spss_1.0 2022', 'agw2022en_spss_1.0 2022', 'hhi2022en_spss_1.0 2022', 'hse2022en_spss_1.0 2022', 'inc2022en_spss_1.0 2022', 'psy2022en_spss_1.0 2022', 'wrk2022en_spss_1.0 2022', 'wth2022en_spss_1.0 2022', 'weights2022en_spss_1.0 2022', 'Data AGI module 2023', 'Data AGW module 2023', 'Data HHI module 2023', 'Data HSE module 2023', 'Data INC module 2023', 'Data PSY module 2023', 'Data WRK module 2023', 'Data WTH module 2023', 'Weights 2023']

In [20]:
# print the first few rows of each DataFrame
for key, df in dataframes.items():
    print(f"DataFrame for {key}:")
    print(df.head())
    print("\n")

DataFrame for agi2022en_spss_1.0 2022:
   nohhold  nomem            ib  winst  winst_c   og  og_c  hprem  hprem_c  \
0      6.0    1.0           NaN    0.0      0.0  0.0   0.0    0.0      0.0
1    106.0    1.0  18733.601910    0.0      0.0  0.0   0.0    0.0      0.0
2    173.0    1.0  11774.812190    0.0      0.0  0.0   0.0    0.0      0.0
3    262.0    2.0  26571.028104    0.0      0.0  0.0   0.0    0.0      0.0
4    268.0    1.0   2165.361210    0.0      0.0  0.0   0.0    0.0      0.0

   beurs  ...  aio  aio_c  aww  aww_c  zvwpremie  zvwpremieb     btot  \
0    0.0  ...  0.0    0.0  NaN    0.0     0.0000      0.0000      NaN
1    0.0  ...  0.0    0.0  0.0    0.0  4064.2700      0.0000  59636.0
2    0.0  ...  0.0    0.0  0.0    0.0  3570.0000      0.0000  51000.0
3    0.0  ...  0.0    0.0  0.0    0.0  3967.1825   3967.1825  76848.4
4    0.0  ...  0.0    0.0  0.0    0.0  1797.7500   1797.7500  28850.0

            ntot     hefkort      box3tax
0            NaN     0.00000     0.000000
1   39282.398090  3391.35409     0.000000
2   37365.187810  7146.18781     0.000000
3  102087.189396     0.00000  5085.070604
4   23134.888790  3373.83879     0.000000

[5 rows x 68 columns]


DataFrame for agw2022en_spss_1.0 2022:
   nohhold  nomem  b1a      b1b  b1c  b2a  b2b  b2c  b3a           b3b  ...  \
0      6.0    1.0  1.0   1400.0  0.0  0.0  0.0  0.0  1.0  21000.000000  ...
1    106.0    1.0  2.0   2550.0  0.0  0.0  0.0  0.0  2.0  14010.000000  ...
2    173.0    1.0  2.0  11750.0  0.0  0.0  0.0  0.0  1.0  14999.999023  ...
3    262.0    2.0  2.0   9081.0  0.0  0.0  0.0  0.0  4.0  29693.000000  ...
4    268.0    1.0  2.0    342.0  0.0  0.0  0.0  0.0  1.0   5000.000000  ...

   b27ogc  b27hya  b27hyb  b27hyc  b27vza  b27vzb  b27vzc  b31a  b31b  b31c
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0

[5 rows x 128 columns]


DataFrame for hhi2022en_spss_1.0 2022:
   nohhold  nomem  gebjaar geslacht                positie  \
0      6.0    1.0   1956.0     Male  head of the household
1    106.0    1.0   1963.0     Male  head of the household
2    106.0    2.0   1968.0   Female                 spouse
3    173.0    1.0   1965.0     Male  head of the household
4    173.0    5.0   1970.0   Female                 spouse

                                              oplzon  \
0  HBO (eerste of tweede fase) / vocational colleges
1  HBO (eerste of tweede fase) / vocational colleges
2  Voorbereidend middelbaar beroepsonderwijs (VMB...
3  MBO of het leerlingwezen / senior vocational t...
4  HBO (eerste of tweede fase) / vocational colleges

                                              oplmet  \
0  HBO (eerste of tweede fase) / vocational colleges
1  HBO (eerste of tweede fase) / vocational colleges
2  Voorbereidend middelbaar beroepsonderwijs (VMB...
3  MBO of het leerlingwezen / senior vocational t...
4  HBO (eerste of tweede fase) / vocational colleges

                          bezighei  aantalhh aantalki  \
0                (partly) disabled  1 person     none
1  employed on a contractual basis  2 people     none
2           works in own household  2 people     none
3  employed on a contractual basis  3 people  1 child
4  employed on a contractual basis  3 people  1 child

                              sted  regio           prov  \
0  very low degree of urbanization  South        Limburg
1       low degree of urbanization  South  Noord-Brabant
2       low degree of urbanization  South  Noord-Brabant
3      high degree of urbanization   East      Flevoland
4      high degree of urbanization   East      Flevoland

                                            woonvorm account kostwin partner  \
0                       is living by himself/herself     yes     yes      no
1  is living together with partner, no child(ren)...     yes     yes     yes
2  is living together with partner, no child(ren)...      no      no     yes
3  is living together with partner, child(ren) li...      no     yes     yes
4  is living together with partner, child(ren) li...     yes      no     yes

                    woning
0        rented house/flat
1  owner-occupied property
2  owner-occupied property
3  owner-occupied property
4  owner-occupied property


DataFrame for hse2022en_spss_1.0 2022:
   nohhold  nomem    weeknr  \
0      6.0    1.0  202219.0
1    106.0    1.0  202219.0
2    173.0    1.0  202220.0
3    262.0    2.0  202219.0
4    268.0    1.0  202219.0

                                                 wo2            won2  \
0               Other sort of accommodation, namely:  seniorenwoning
1  Single-family-house, end terrace house (corner...
2     Single-family-house, terrace house (row house)
3         Apartment, (upstairs or ground-floor) flat
4     Single-family-house, terrace house (row house)

                     wo4     wo5     wo1               wod204 wod204a  ...  \
0  Between 2000 and 2004  2022.0  Tenant  Housing corporation          ...
1  Between 1980 and 1984  1995.0   Owner                  NaN          ...
2  Between 1985 and 1989  1996.0   Owner                  NaN          ...
3  Between 1995 and 1999  2004.0   Owner                  NaN          ...
4  Between 1965 and 1969  1976.0   Owner                  NaN          ...

  hyaflbedr10 hp35 hp75 hp85 hp95 hp45 hp65 hyd6a10 hyd6f10    duur
0         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN   466.0
1         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN   417.0
2         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN   359.0
3         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  1184.0
4         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN   863.0

[5 rows x 262 columns]


DataFrame for inc2022en_spss_1.0 2022:
   nohhold  nomem    weeknr   gez1   gez2       gez3            gez4 gez5  \
0      6.0    1.0  202215.0  176.0   72.0       Good  About the same  Yes
1    106.0    1.0  202215.0  182.0  102.0       Good  About the same  Yes
2    173.0    1.0  202216.0  193.0   96.0  Excellent  About the same   No
3    262.0    2.0  202215.0  182.0   85.0       Good  About the same   No
4    268.0    1.0  202215.0  168.0   85.0       Good  About the same   No

  gez7 gez8  ... pro2  dnbbaan  laagpr  hoogpr   pr0  pr1a  pr2a  pr3a  pr4a  \
0   No  NaN  ...  0.0      NaN     NaN     NaN   8.0  10.0  60.0  25.0   5.0
1   No  NaN  ...  0.0      1.0     8.0    12.0   5.0   0.0   1.0   3.0   2.0
2   No  NaN  ...  0.0      0.0    10.0    20.0  15.0  25.0  25.0  25.0  25.0
3   No  NaN  ...  0.0      NaN     5.0    14.0   9.0   2.0  10.0  60.0  15.0
4   No  NaN  ...  0.0      NaN     8.0    12.0   6.0   0.0  50.0   5.0   0.0

     duur
0  1064.0
1   821.0
2   400.0
3  1928.0
4   851.0

[5 rows x 216 columns]


DataFrame for psy2022en_spss_1.0 2022:
   nohhold  nomem    weeknr                           inkhh  inknorm  \
0      6.0    1.0  202211.0  between 22,000 and 40,000 Euro  Regular
1    106.0    1.0  202211.0  between 40,000 and 75,000 euro      NaN
2    173.0    1.0  202224.0  between 40,000 and 75,000 euro  Regular
3    175.0    1.0  202211.0  between 14,000 and 22,000 Euro  Regular
4    262.0    2.0  202212.0  between 40,000 and 75,000 euro  Regular

                       inkrond                      finsitu  \
0  it is neither hard nor easy  it is just about manageable
1  it is neither hard nor easy          some money is saved
2                   it is easy          some money is saved
3                   it is hard    need to draw upon savings
4                   it is easy          some money is saved

                                           inkeven inkaank inksec  ... pref1  \
0  the expenditures were about equal to the income     NaN    NaN  ...     2
1      the expenditures were lower than the income     NaN    NaN  ...     3
2      the expenditures were lower than the income     NaN    NaN  ...     3
3  the expenditures were about equal to the income     NaN    NaN  ...     6
4      the expenditures were lower than the income     NaN    NaN  ...     6

                              pref2  pref3 jeugd1_x jeugd2_x jeugd3_x  \
0                                 2  250.0      NaN      NaN      NaN
1                                 2    0.0      NaN      NaN      NaN
2                                 2    0.0      NaN      NaN      NaN
3  not at all willing to take risks   10.0      NaN      NaN      NaN
4                                 6   50.0      NaN      NaN      NaN

  jeugd4_x jeugd5_x jeugd6_x       duur
0      NaN      NaN      NaN     1240.0
1      NaN      NaN      NaN     1018.0
2      NaN      NaN      NaN  6028104.0
3      NaN      NaN      NaN      780.0
4      NaN      NaN      NaN   130601.0

[5 rows x 133 columns]


DataFrame for wrk2022en_spss_1.0 2022:
   nohhold  nomem    weeknr  \
0      6.0    1.0  202213.0
1    106.0    1.0  202213.0
2    173.0    1.0  202216.0
3    262.0    2.0  202213.0
4    268.0    1.0  202213.0

                                              burgst    jrbs   kk  hkk kidout  \
0                               Divorced from spouse  2019.0   No  NaN     No
1  Married or registered partnership (including s...  1989.0   No  NaN    Yes
2  Married or registered partnership (including s...  2022.0   No  NaN    Yes
3  Married or registered partnership (including s...  1985.0  Yes  3.0     No
4                               Divorced from spouse  2015.0  Yes  1.0     No

   hkidout gesl01  ... netloon perloon xminl2jn mloon mloonp loonm perloonm  \
0      NaN    NaN  ...     NaN     NaN      NaN   NaN    NaN   NaN      NaN
1      2.0    NaN  ...     NaN     NaN      NaN   NaN    NaN   NaN      NaN
2      2.0    NaN  ...     NaN     NaN      NaN   NaN    NaN   NaN      NaN
3      NaN    NaN  ...     NaN     NaN      NaN   NaN    NaN   NaN      NaN
4      NaN    NaN  ...     NaN     NaN      NaN   NaN    NaN   NaN      NaN

  hloonv loonvp    duur
0    NaN    NaN  1395.0
1    NaN    NaN   505.0
2    NaN    NaN  1757.0
3    NaN    NaN  1087.0
4    NaN    NaN   686.0

[5 rows x 281 columns]


DataFrame for wth2022en_spss_1.0 2022:
   nohhold  nomem    weeknr  \
0      6.0    1.0  202223.0
1    106.0    1.0  202223.0
2    173.0    1.0  202232.0
3    262.0    2.0  202223.0
4    268.0    1.0  202223.0

                                                bzr1 bzr1a bzr1b bz01  bet2  \
0  no (declared unfit for work, unemployed, (earl...   NaN   NaN  yes   1.0
1  yes, employed by a foundation or cooperation (...   NaN   NaN  yes   2.0
2  yes, employed by a cooperation or another kind...   NaN   NaN  yes   2.0
3  no (declared unfit for work, unemployed, (earl...   NaN   NaN  yes   2.0
4  no (declared unfit for work, unemployed, (earl...   NaN   NaN  yes   2.0

                                               bet91 bet101  ... krediet2  \
0           the account is registered in my own name         ...       no
1  the account is registered jointly in my own na...         ...       no
2           the account is registered in my own name         ...       no
3  the account is registered jointly in my own na...         ...       no
4           the account is registered in my own name         ...       no

  krediet3 krediet4 andkred nokred1 nokred2 nokred3 afgezien verwkred   duur
0       no       no             NaN     NaN     NaN       no      yes  314.0
1       no       no             NaN     NaN     NaN       no      yes  246.0
2       no       no             NaN     NaN     NaN       no      yes  220.0
3       no       no             NaN     NaN     NaN       no      yes  552.0
4       no       no             NaN     NaN     NaN       no      yes  323.0

[5 rows x 613 columns]


DataFrame for weights2022en_spss_1.0 2022:
   nohhold owner          idink         idink2  decil   popfreq      wgth
0      6.0    no   18822.814453            NaN    2.0  0.089524  1.655831
1    106.0   yes   33897.097656            NaN    5.0  0.063558  0.698519
2    173.0   yes   44646.632812   43366.171875    6.0  0.070477  0.735482
3    175.0   yes    8033.073730            NaN    1.0  0.009046  0.109460
4    262.0   yes  104209.664062  104209.664062   10.0  0.092594  1.462853


DataFrame for Data AGI module 2023:
   nohhold  nomem            ib  winst  winst_c   og  og_c  hprem  hprem_c  \
0      6.0    1.0           NaN    0.0      0.0  0.0   0.0    0.0      0.0
1    106.0    1.0  16512.731370    0.0      0.0  0.0   0.0    0.0      0.0
2    262.0    2.0   8565.506107    0.0      0.0  0.0   0.0    0.0      0.0
3    268.0    1.0   1928.418920    0.0      0.0  0.0   0.0    0.0      0.0
4    338.0    2.0           NaN    0.0      0.0  0.0   0.0    0.0      0.0

   beurs  ...  aio  aio_c  aww  aww_c  zvwpremie  zvwpremieb     btot  \
0    0.0  ...  0.0    0.0  NaN    0.0       0.00        0.00      NaN
1    0.0  ...  0.0    0.0  0.0    0.0    3645.00        0.00  55539.0
2    0.0  ...  0.0    0.0  0.0    0.0    2120.23     2120.23  37893.5
3    0.0  ...  0.0    0.0  0.0    0.0    1754.25     1754.25  28100.0
4    0.0  ...  0.0    0.0  0.0    0.0       0.00        0.00      NaN

           ntot     hefkort      box3tax
0           NaN     0.00000     0.000000
1           NaN  4075.57593     0.000000
2  23355.763893  2816.28212  4803.411027
3  23545.331080  3458.35108     0.000000
4           NaN     0.00000     0.000000

[5 rows x 68 columns]


DataFrame for Data AGW module 2023:
   nohhold  nomem  b1a     b1b  b1c  b2a  b2b  b2c  b3a      b3b  ...  b27ogc  \
0      6.0    1.0  1.0  1400.0  0.0  0.0  0.0  0.0  3.0  98000.0  ...     0.0
1    106.0    1.0  2.0  2550.0  0.0  0.0  0.0  0.0  2.0  21010.0  ...     0.0
2    262.0    2.0  2.0  9681.0  0.0  0.0  0.0  0.0  4.0  29507.0  ...     0.0
3    268.0    1.0  2.0   342.0  0.0  0.0  0.0  0.0  1.0   5000.0  ...     0.0
4    338.0    2.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0      0.0  ...     0.0

   b27hya  b27hyb  b27hyc  b27vza  b27vzb  b27vzc  b31a  b31b  b31c
0     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
1     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
2     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
3     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
4     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0

[5 rows x 128 columns]


DataFrame for Data HHI module 2023:
   nohhold  nomem  gebjaar geslacht                positie  \
0      6.0    1.0   1956.0     Male  head of the household
1    106.0    1.0   1963.0     Male  head of the household
2    106.0    2.0   1968.0   Female                 spouse
3    262.0    1.0   1933.0   Female                 spouse
4    262.0    2.0   1935.0     Male  head of the household

                                              oplzon  \
0  HBO (eerste of tweede fase) / vocational colleges
1  HBO (eerste of tweede fase) / vocational colleges
2  Voorbereidend middelbaar beroepsonderwijs (VMB...
3  Kleuter-, lager- of basisonderwijs / kindergar...
4                HAVO/VWO / pre-university education

                                              oplmet  \
0  HBO (eerste of tweede fase) / vocational colleges
1  HBO (eerste of tweede fase) / vocational colleges
2  Voorbereidend middelbaar beroepsonderwijs (VMB...
3  Kleuter-, lager- of basisonderwijs / kindergar...
4                HAVO/VWO / pre-university education

                          bezighei  aantalhh aantalki  \
0  retired [pre-retired, AOW, VUT]  1 person     none
1  employed on a contractual basis  2 people     none
2           works in own household  2 people     none
3           works in own household  2 people     none
4  retired [pre-retired, AOW, VUT]  2 people     none

                              sted                 regio           prov  \
0  very low degree of urbanization                 South        Limburg
1       low degree of urbanization                 South  Noord-Brabant
2       low degree of urbanization                 South  Noord-Brabant
3      high degree of urbanization  Three largest cities   Zuid-Holland
4      high degree of urbanization  Three largest cities   Zuid-Holland

                                            woonvorm account kostwin partner  \
0                       is living by himself/herself     yes     yes      no
1  is living together with partner, no child(ren)...     yes     yes     yes
2  is living together with partner, no child(ren)...      no      no     yes
3  is living together with partner, no child(ren)...      no      no     yes
4  is living together with partner, no child(ren)...     yes     yes     yes

                    woning
0        rented house/flat
1  owner-occupied property
2  owner-occupied property
3  owner-occupied property
4  owner-occupied property


DataFrame for Data HSE module 2023:
   nohhold  nomem    weeknr  \
0      6.0    1.0  202319.0
1    106.0    1.0  202319.0
2    262.0    2.0  202319.0
3    268.0    1.0  202319.0
4    338.0    2.0  202320.0

                                                 wo2            won2  \
0               Other sort of accommodation, namely:  seniorenwoning
1  Single-family-house, end terrace house (corner...
2         Apartment, (upstairs or ground-floor) flat
3     Single-family-house, terrace house (row house)
4         Apartment, (upstairs or ground-floor) flat

                     wo4     wo5     wo1               wod204 wod204a  ...  \
0  Between 2000 and 2004  2022.0  Tenant  Housing corporation          ...
1  Between 1980 and 1984  1995.0   Owner                  NaN          ...
2  Between 1995 and 1999  2004.0   Owner                  NaN          ...
3  Between 1965 and 1969  1976.0   Owner                  NaN          ...
4  Between 1990 and 1994  2012.0  Tenant  Housing corporation          ...

  hyaflbedr10 hp35 hp75 hp85 hp95 hp45 hp65 hyd6a10 hyd6f10   duur
0         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  322.0
1         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  387.0
2         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  915.0
3         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  470.0
4         NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN     NaN  267.0

[5 rows x 262 columns]


DataFrame for Data INC module 2023:
   nohhold  nomem    weeknr   gez1   gez2  gez3            gez4 gez5 gez7  \
0      6.0    1.0  202315.0  176.0   70.0  Good  Somewhat worse  Yes   No
1    106.0    1.0  202315.0  182.0  103.0  Good  About the same  Yes   No
2    262.0    2.0  202315.0  182.0   86.0  Good  About the same   No   No
3    268.0    1.0  202315.0  168.0   85.0  Good  About the same   No   No
4    338.0    2.0  202315.0  172.0   95.0  Good  About the same   No   No

  gez8  ...   pro2  dnbbaan  laagpr  hoogpr   pr0   pr1a  pr2a   pr3a  pr4a  \
0  NaN  ...    0.0      NaN     3.0     3.8   3.0    0.0  25.0   35.0   1.0
1  NaN  ...   10.0      1.0    12.0    20.0  10.0    5.0   5.0    5.0   5.0
2  NaN  ...    0.0      NaN     3.9     6.1   5.0    0.0  70.0   50.0   5.0
3  NaN  ...  100.0      NaN     6.0     8.0   5.0  100.0  80.0   50.0  10.0
4  NaN  ...    NaN      NaN     4.2     6.5   5.0    0.0   5.0  100.0  10.0

     duur
0  1377.0
1   431.0
2  1671.0
3  1068.0
4  1113.0

[5 rows x 215 columns]


DataFrame for Data PSY module 2023:
   nohhold  nomem    weeknr                           inkhh  inknorm  \
0      6.0    1.0  202311.0  between 22,000 and 40,000 Euro  Regular
1    106.0    1.0  202311.0  between 22,000 and 40,000 Euro      NaN
2    262.0    2.0  202311.0  between 40,000 and 75,000 euro  Regular
3    268.0    1.0  202311.0  between 14,000 and 22,000 Euro  Regular
4    338.0    2.0  202312.0  between 14,000 and 22,000 Euro  Regular

                       inkrond                               finsitu  \

In [29]:
dataframes['agi2022en_spss_1.0 2022']

,nohhold,nomem,ib,winst,winst_c,og,og_c,hprem,hprem_c,beurs,...,aio,aio_c,aww,aww_c,zvwpremie,zvwpremieb,btot,ntot,hefkort,box3tax
0,6.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.000,0.000,NaN,NaN,0.00000,0.000000
1,106.0,1.0,16512.731370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3645.000,0.000,55539.0,NaN,4075.57593,0.000000
2,262.0,2.0,8565.506107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2120.230,2120.230,37893.5,23355.763893,2816.28212,4803.411027
3,268.0,1.0,1928.418920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1754.250,1754.250,28100.0,23545.331080,3458.35108,0.000000
4,338.0,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000,0.000,NaN,NaN,0.00000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,89829.0,2.0,-250.728500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,776.250,776.250,11500.0,NaN,2455.27850,0.000000
2519,89942.0,1.0,1309.759200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1350.000,0.000,20000.0,24150.240800,6104.24080,0.000000
2520,89942.0,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.000,0.000,NaN,NaN,1309.75920,0.000000
2521,89966.0,1.0,7459.413760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2925.045,2925.045,43334.0,31150.541240,2254.83304,0.000000
2522,89975.0,1.0,16828.516340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3780.000,0.000,56000.0,36903.483660,3930.68366,0.000000

In [30]:
dataframes['Data AGI module 2023']

,nohhold,nomem,ib,winst,winst_c,og,og_c,hprem,hprem_c,beurs,...,aio,aio_c,aww,aww_c,zvwpremie,zvwpremieb,btot,ntot,hefkort,box3tax
0,6.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.000,0.000,NaN,NaN,0.00000,0.000000
1,106.0,1.0,16512.731370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3645.000,0.000,55539.0,NaN,4075.57593,0.000000
2,262.0,2.0,8565.506107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2120.230,2120.230,37893.5,23355.763893,2816.28212,4803.411027
3,268.0,1.0,1928.418920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1754.250,1754.250,28100.0,23545.331080,3458.35108,0.000000
4,338.0,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000,0.000,NaN,NaN,0.00000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,89829.0,2.0,-250.728500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,776.250,776.250,11500.0,NaN,2455.27850,0.000000
2519,89942.0,1.0,1309.759200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1350.000,0.000,20000.0,24150.240800,6104.24080,0.000000
2520,89942.0,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.000,0.000,NaN,NaN,1309.75920,0.000000
2521,89966.0,1.0,7459.413760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2925.045,2925.045,43334.0,31150.541240,2254.83304,0.000000
2522,89975.0,1.0,16828.516340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3780.000,0.000,56000.0,36903.483660,3930.68366,0.000000